apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirth-connect
  labels:
    app: mirth-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirth-connect
  template:
    metadata:
      labels:
        app: mirth-connect
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: mirth-connect
          image: minidu0th/mirth-jmx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 8080
              name: http
            - containerPort: 9404  
              name: metrics
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: mirth-connect
spec:
  selector:
    app: mirth-connect
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: https
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 9404
      targetPort: 9404
      name: metrics
  type: ClusterIP